---
- name: Installing and Configuring Web Server on target node
  # Hosts Section
  hosts: 
  - target  
  # Tasks Section
  tasks:
  - name: Installing Nginx Web Server
    yum:
      update_cache: yes
      name: nginx
      state: latest
  - name: Copying the index.html file
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  - name: Start the service
    service:
      name: nginx
      state: started
      enabled: yes
